# Generated by Django 4.1.7 on 2024-01-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messsage',
            new_name='Message',
        ),
    ]
